name: Run Dummy Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Sjekk ut repo
        uses: actions/checkout@v3

      - name: Sett opp Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Kjør kun dummy-test
        run: python -m pytest tests/test_dummy.py -v
