name: Run Pytest

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Sjekk ut repo
        uses: actions/checkout@v3

      - name: Sett opp Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer avhengigheter
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Kjør pytest
        run: python -m pytest tests -v
