name: Release

on:
  push:
    tags:
      - 'v*.*.*'   # kjører når du pusher en tag som v0.1.0, v0.2.0 osv.

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Sjekk ut repo
        uses: actions/checkout@v3

      - name: Opprett GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
